FROM ghcr.io/open-webui/open-webui:main

RUN pip install -U ddgs

COPY secret-entrypoint.sh /usr/local/bin/clare-secret-entrypoint
COPY managed_config.py /usr/local/lib/clare-open-webui-managed-config.py
RUN chmod 0755 /usr/local/bin/clare-secret-entrypoint

ENTRYPOINT ["/usr/local/bin/clare-secret-entrypoint"]
